modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
    modId="structure_advancer_tool"
    version="${file.jarVersion}"
    displayName="S.A.T."
    displayURL="https://github.com/MantisYT5818/structure_advancer_tool/"
    authors="Saisho/MantisYT123"

[[dependencies.structure_advancer_tool]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
[[dependencies.structure_advancer_tool]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

